protocol = "watchdog"
doc = ""
traits = ["is-sensor", "is-daemon"]

[links]
source = "https://github.com/yaq-project/yaqd-watchdog"
bugtracker = "https://github.com/yaq-project/yaqd-watchdog/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-watchdog"

[[types]]
type = "record"
name = "check_online"
fields = [{"name"="host", "type"="string", "default"="localhost"},
          {"name"="port", "type"="int"},
          {"name"="online", "type"="boolean"},
          {"name"="timeout", "type"="int", "default"=10, "doc"="seconds"}]

[[types]]
type = "record"
name = "check_position_absolute"
fields = [{"name"="host", "type"="string", "default"="localhost"},
          {"name"="port", "type"="int"},
          {"name"="under", "type"=["float", "null"], default="__null__"},
          {"name"="over", "type"=["float", "null"], default="__null__"},
          {"name"="timeout", "type"="int", "default"=10, "doc"="seconds"}]

[[types]]
type = "record"
name = "check_position_percentage"
fields = [{"name"="host", "type"="string", "default"="localhost"},
          {"name"="port", "type"="int"},
          {"name"="percent_under", "type"=["float", "null"], default="__null__"},
          {"name"="percent_over", "type"=["float", "null"], default="__null__"},
          {"name"="timeout", "type"="int", "default"=10, "doc"="seconds"}]

[[types]]
type = "record"
name = "set_position"
fields = [{"name"="host", "type"="string", "default"="localhost"},
          {"name"="port", "type"="int"},
          {"name"="position", "type"="float"}]

[[types]]
type = "record"
name = "set_relative"
fields = [{"name"="host", "type"="string", "default"="localhost"},
          {"name"="port", "type"="int"},
          {"name"="distance", "type"="float"}]

[[types]]
type = "record"
name = "set_identifier"
fields = [{"name"="host", "type"="string", "default"="localhost"},
          {"name"="port", "type"="int"},
          {"name"="identifier", "type"="string"}]

[config]

[config.online_checks]
type = "map"
values = "check_online"
default = {}

[config.absolute_position_checks]
type = "map"
values = "check_position_absolute"
default = {}

[config.percentage_position_checks]
type = "map"
values = "check_position_percentage"
default = {}

[config.set_position_actions]
type = "map"
values = "set_position"
default = {}

[config.set_relative_actions]
type = "map"
values = "set_relative"
default = {}

[config.set_identifier_actions]
type = "map"
values = "set_identifier"
default = {}

[state]

[messages]
